### ISSUE TITLE
request: expose the underlying connection

### ISSUE THREAD

**Issue by AshfordN** [webrtc-rs/ice#19]
I'd like to use this crate to establish a peer-to-peer connection between clients, but after that I'd like to obtain the underlying (udp) connection.

**Comment by melekes** [comment]
Could you tell what specific API changes you'd like to see? You mean you want to get back the original UDP socket after you've transferred ownership to UDP mux?

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
