### ISSUE TITLE
ping_pong example has incorrect content encoding

### ISSUE THREAD

**Issue by Silvea12** [webrtc-rs/ice#23]
Hey! I'm just browsing the ping_pong example here, and noticed something strange: The request to /remoteCandidate has a `content-type` of `application/json` but the data being sent is not JSON. I'm not sure what format it is meant to be or else I'd be doing a PR instead, but regardless this seems wrong as the format is not JSON-based.

**Comment by rainliu** [comment]
yes, it uses customized format, not actual json.

sure, PR is welcomed to fix it.
