### ISSUE TITLE
q: Would it be possible to expose UDPMuxConn and UDPMuxConnParams?

### ISSUE THREAD

**Issue by melekes** [webrtc-rs/ice#26]
I've made some changes to the `UDPMuxDefault` ([link](https://github.com/libp2p/rust-libp2p/pull/2622/files#diff-947bc76535b57b88959cee7a67a2ee0c8a3acf91ea796358c310a8b718782abe)) and had to copy `UDPMuxConn`, `UDPMuxConnParams` and socket_addr_ext.rs as well.

Would you agree to expose `UDPMuxConn` and `UDPMuxConnParams` so that people can tweak `UDPMuxDefault` (read create alternative UDP muxes) ? Thanks 🙏

**Comment by k0nserv** [comment]
I don't see why not. It might be easier to think through the implications if you propose the changes as PR?
