### ISSUE TITLE
[Windows/Mac] re-enable mdns_test.rs once mdns crate fixed port re-use issue in non-linux platforms

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/ice#4]

**Comment by metaclips** [comment]
Are we still having this issue?

**Comment by rainliu** [comment]
I haven’t tried it. Could you try it on windows?

**Comment by rainliu** [comment]
@metaclips, it works on windows/mac, but have to change default sever address to "0.0.0.0"

**Comment by metaclips** [comment]
I think it's best we use the INADDR_ANY wildcard instead of specifying separate addresses on windows and unix
